### ISSUE TITLE
Gcode to x3g?

### ISSUE THREAD

**Issue by Wilde-Bill** [Toylerrr/Flashforge-for-Cura#12]
How do I convert Gcode to the x3g my creator pro uses

**Comment by Toylerrr** [comment]
https://marketplace.ultimaker.com/app/cura/plugins/Ghostkeeper/X3GWriter

**Comment by Wilde-Bill** [comment]
Wait how do I do this?

**Comment by Wilde-Bill** [comment]
I added it to cura but I cannot save it, it's not a gcode flavor, and when I hit save I can only use 3mf, gcode or obj or stl? I have very little Idea what Im doing btw.

**Comment by Wilde-Bill** [comment]
Nevermind Ghostkeeper helped me

**Comment by Wilde-Bill** [comment]
Never-mind, but now my printer just zeroes itself, then the bed goes to the bottom and the printer prints in the corner not the correct location.
