### ISSUE TITLE
Cura 4.1 wont print 

### ISSUE THREAD

**Issue by Toylerrr** [Toylerrr/Flashforge-for-Cura#3]
Something is causing to hang at the extruder heating point but not with octoprint

**Comment by Toylerrr** [comment]
Seems like a start Gcode Error

**Comment by Meins321** [comment]
This works fine with cura 4.2.1:
https://www.thingiverse.com/thing:3569113/files

but not for dual maybe you know how to make it work like flashprint, just run a thin line to the side and print dual extruder

**Comment by Toylerrr** [comment]
Fixed b/c Gcode
