### ISSUE TITLE
Def.json issue

### ISSUE THREAD

**Issue by eskeyaar** [Toylerrr/Flashforge-for-Cura#4]
In your def.json for the machine definition, you have to use Makerbot as your gcode flavor, not reprap.
Since FFCP is Sailfish firmware, not marlin.

**Comment by Toylerrr** [comment]
I have tested the gcode flavor and the creator of GPX has stated that he prefers to use RepRap (http://markwal.github.io/programming/2016/02/18/ffcp-start-and-end-gcode.html) instead of makerbot.
