### ISSUE TITLE
Hoping to get help

### ISSUE THREAD

**Issue by bossrhino** [Toylerrr/Flashforge-for-Cura#7]
Sent a message on Discord.  Hoping to get some help with my Printer.  Wondering if you could assist.

**Comment by Toylerrr** [comment]
Hey Boss I dont see any message on Discord try again Toylerrr#9601

**Comment by bossrhino** [comment]
Aw, sorry.  Meant to say friend request.  Thank you so much :)

**Comment by bossrhino** [comment]
bossrhino#0938

Discord tag.
